config/routes.rb
Agora::Application.routes.draw do
  get "sessions/create" => "sessions#create", :as => :create_session
  get "sessions/destroy" => "sessions#destroy", :as => :destroy_session

  get "categories/search" => "categories#search", :as => :search_categories

  get "users/edit" => "users#edit", :as => :edit_user
  get "users/get_reset_key" => "users#get_reset_key", :as => :get_reset_key
  post "users/send_reset_key" => "users#send_reset_key", :as => :send_reset_key
  get "users/reset_password/:id/:reset_key" => "users#reset_password", :as => :reset_password

  get "topics/new/:category_id" => "topics#new", :as => :new_topic

  get "categories/:id/subscribe" => "categories#subscribe", :as => :subscribe_category
  get "categories/:id/unsubscribe" => "categories#unsubscribe", :as => :unsubscribe_category

  post "comments/:id/reply" => "comments#reply", :as => :reply_comment
  get "comments/:id/delete" => "comments#delete", :as => :delete_comment

  post "topics/vote/:id/:positive" => "topics#vote", :as => :vote_topic
  post "comments/vote/:id/:positive" => "comments#vote", :as => :vote_comment

  resources :users
  resources :categories
  resources :topics
  resources :comments

  root :to => 'categories#show'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  belongs_to :parent, :class_name => Comment
  has_many :comment_votes
  attr_accessible :text, :topic, :topic_id, :user, :parent, :parent_id
  validates :text, :presence => true
  validates :topic_id, :presence => true
  validates :user_id, :presence => true

  def positive_votes
    CommentVote.where(:comment_id => self.id, :positive => true).count
  end

  def negative_votes
    CommentVote.where(:comment_id => self.id, :positive => false).count
  end

  def votes
    positive_votes - negative_votes
  end

  def user_voted?(user)
    if user
      CommentVote.find_by_user_id_and_comment_id user.id, self.id
    end
  end

  def set_deleted(user)
    if user == self.user
      self.deleted = true
      self.save
    else
      false
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    if current_user
      @comment = Comment.new(params[:comment])
      @comment.user = current_user
      if @comment.save
        if @comment.user != @comment.topic.user && @comment.topic.user.comment_notification
          UserMailer.comment_notification(@comment).deliver
        end
        flash[:notice] = "Comment submitted."
      else
        flash[:error] = "Unable to submit comment."
      end
      redirect_to :back
    else
      flash[:error] = "You have to be logged in to access this page."
      redirect_to :root
    end
  end

  def update
    if current_user
      @comment = Comment.find params[:id]
      @comment.text = params[:comment][:text]
      if @comment.user == session[:user] && @comment.save
        flash[:notice] = "Comment edited."
      else
        flash[:error] = "Unable to edit comment."
      end
      redirect_to :back
    else
      flash[:error] = "You have to be logged in to access this page."
      redirect_to :root
    end
  end

  def delete
    if current_user
      @comment = Comment.find params[:id]
      if @comment && @comment.user == current_user && @comment.set_deleted(session[:user])
        flash[:notice] = "Comment deleted."
      else
        flash[:error] = "Unable to delete comment."
      end
      redirect_to :back
    else
      flash[:error] = "You have to be logged in to access this page."
      redirect_to :root
    end
  end

  def reply
    if current_user
      @parent = Comment.find params[:id]
      @comment = Comment.new params[:comment]
      @comment.user = current_user
      @comment.topic = @parent.topic
      @comment.parent = @parent
      if @comment.save
        if @comment.parent && @comment.parent.user != @comment.user && @comment.parent.user.reply_notification
          UserMailer.reply_notification(@comment).deliver
        end
        flash[:notice] = "Reply submitted."
      else
        flash[:error] = "Unable to submit reply."
      end
      redirect_to :back
    else
      flash[:error] = "You have to be logged in to access this page."
      redirect_to :root
    end
  end

  def vote
    if current_user
      @comment = Comment.find params[:id]
      positive = params[:positive]
      if !@comment.user_voted?(session[:user])
        @vote = CommentVote.new(:user_id => session[:user].id, :comment_id => @comment.id, :positive => positive)
        if @vote.save
          flash[:notice] = "Vote recorded."
        else
          flash[:error] = "Unable to record vote."
        end
      end
      redirect_to :back
    else
      flash[:error] = "You have to be logged in to access this page."
      redirect_to :root
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="container">
  <a id="c<%= comment.id %>"></a>
  <% if comment.deleted %>
    <p class="deleted_comment">Comment deleted.</p>
  <% else %>
    <div class="votes_container">
      <div class="votes">
        <%= button_to "+", vote_comment_url(comment.id, "true"), :class => "vote_button", :disabled => !current_user || comment.user_voted?(current_user) %>
        <%= comment.votes %><br/>
        <%= button_to "-", vote_comment_url(comment.id, "false"), :class => "vote_button", :disabled => !current_user || comment.user_voted?(current_user) %>
      </div>
    </div>
    <div class="data_container">
      <div class="data">
        <p><%= comment.text %></p>
        Written by <%= link_to comment.user.name, user_url(comment.user), :class => "user_link" %> at <%= l comment.created_at, :format => :long %>
        <% if comment.created_at != comment.updated_at %>
          updated at <%= l comment.updated_at, :format => :long %>
        <% end %>
        <% if include_topic %>
          <br /><%= link_to comment.topic.title, topic_url(comment.topic), :class => "topic_link" %> in <%= link_to comment.topic.category.name, category_url(comment.topic.category) %>
        <% end %>
        <br />
        <%= link_to "Permalink", "#{topic_url(comment.topic)}#c#{comment.id}" %>
        <% if current_user %>
          <a href="#" class="reply_link">Reply</a>
          <% if current_user.id == comment.user.id %>
            <a href="#" class="edit_comment_link">Edit</a>&nbsp;<%= link_to "Delete", delete_comment_url(comment), :confirm => "Are you sure?" %>
          <% end %>
          <%= form_for(Comment.new, :url => reply_comment_path(comment), :html => { :class => "reply_form", :hidden => true }) do |f| %>
            <%= f.text_area :text, :cols => 50, :rows => 5, :placeholder => "Reply to this comment." %><br />
            <%= f.submit "Submit" %>&nbsp;<%= button_tag "Cancel", :type => "button", :class => "cancel_reply" %>
          <% end %>
          <%= form_for comment, :html => { :class => "edit_comment_form", :hidden => true } do |f| %>
            <%= f.text_area :text, :cols => 50, :rows => 5, :placeholder => "Edit this comment." %><br />
            <%= f.submit "Submit" %>&nbsp;<%= button_tag "Cancel", :type => "button", :class => "cancel_edit" %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>