config/routes.rb
Agora::Application.routes.draw do
  get "sessions/create" => "sessions#create", :as => :create_session
  get "sessions/destroy" => "sessions#destroy", :as => :destroy_session

  get "categories/search" => "categories#search", :as => :search_categories

  get "users/edit" => "users#edit", :as => :edit_user
  get "users/get_reset_key" => "users#get_reset_key", :as => :get_reset_key
  post "users/send_reset_key" => "users#send_reset_key", :as => :send_reset_key
  get "users/reset_password/:id/:reset_key" => "users#reset_password", :as => :reset_password

  get "topics/new/:category_id" => "topics#new", :as => :new_topic

  get "categories/:id/subscribe" => "categories#subscribe", :as => :subscribe_category
  get "categories/:id/unsubscribe" => "categories#unsubscribe", :as => :unsubscribe_category

  post "comments/:id/reply" => "comments#reply", :as => :reply_comment
  get "comments/:id/delete" => "comments#delete", :as => :delete_comment

  post "topics/vote/:id/:positive" => "topics#vote", :as => :vote_topic
  post "comments/vote/:id/:positive" => "comments#vote", :as => :vote_comment

  resources :users
  resources :categories
  resources :topics
  resources :comments

  root :to => 'categories#show'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :comments
  has_many :topic_votes
  attr_accessible :description, :title, :category, :category_id, :user
  validates :title, :presence => true
  validates :description, :presence => true
  validates :user_id, :presence => true
  validates :category_id, :presence => true

  def self.search(query)
    if query.blank?
      nil
    else
      find :all, :conditions => ["title LIKE ?", "%#{ query }%"]
    end
  end

  def positive_votes
    TopicVote.where(:topic_id => self.id, :positive => true).count
  end

  def negative_votes
    TopicVote.where(:topic_id => self.id, :positive => false).count
  end

  def votes
    positive_votes - negative_votes
  end

  def user_voted?(user)
    if user
      TopicVote.find_by_user_id_and_topic_id user.id, self.id
    end
  end

  def grouped_comments
    comments.sort_by{|c| c.votes }.reverse.group_by{|c| c.parent_id }
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def show
    @topic = Topic.find params[:id]
    @comments = @topic.grouped_comments
    if current_user
      @comment = Comment.new
    end
  end

  def new
    category = params[:category_id] ? Category.find(params[:category_id]) : Category.first

    @topic = Topic.new
    @topic.category = category
  end

  def create
    if current_user
      @topic = Topic.new(params[:topic])
      @topic.user = current_user
      if @topic.save
        flash[:notice] = "Topic created."
        redirect_to topic_url(@topic)
      else
        render :new
      end
    else
      flash[:error] = "You have to be logged in to access this page."
      redirect_to :root
    end
  end

  def vote
    if current_user
      @topic = Topic.find params[:id]
      positive = params[:positive] == "true"
      unless TopicVote.find_by_user_id_and_topic_id current_user.id, @topic.id
        @vote = TopicVote.new(:user_id => current_user.id, :topic_id => @topic.id, :positive => positive)
        if @vote.save
          flash[:notice] = "Vote recorded."
        else
          flash[:error] = "Unable to record vote."
        end
      end
      redirect_to :back
    else
      flash[:error] = "You have to be logged in to access this page."
      redirect_to :root
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def for_each_children(comments, comment_id, before, after)
    s = ""
    children = comments[comment_id]
    if children
      comments[comment_id].each do |child|
        s += before
        s += yield child
        s += for_each_children(comments, child.id, before, after) {|c| yield c}
        s += after
      end
    end
    s.html_safe
  end
end

app/views/topics/_topic.html.erb
<div class="container">
  <div class="votes_container">
    <div class="votes">
      <%= button_to "+", vote_topic_url(topic.id, "true"), :class => "vote_button", :disabled => !current_user || topic.user_voted?(current_user) %>
      <%= topic.votes %><br/>
      <%= button_to "-", vote_topic_url(topic.id, "false"), :class => "vote_button", :disabled => !current_user || topic.user_voted?(current_user) %>
    </div>
  </div>
  <div class="data_container">
    <div class="data">
      <p><%= link_to topic.title, topic_url(topic), :class => "topic_link" %> in <%= link_to topic.category.name, category_url(topic.category) %> (<%= pluralize(topic.comments.size, "comment") %>)<br />
      Created by <%= link_to topic.user.name, user_url(topic.user), :class => "user_link" %> at <%= l topic.created_at, :format => :long %></p>
    </div>
  </div>
</div>

app/views/topics/new.html.erb
<%= render "/shared/error_messages", :target => @topic %>

<p><%= link_to "Main", "/" %> &gt; <%= link_to @topic.category.name, category_url(@topic.category) %> &gt; Create new topic</p>

<%= form_for @topic do |f| %>
  <p>
    <%= f.label :title, :class => "form_label" %>
    <%= f.text_field :title %><br />
    <%= f.label :category_id, "Category", :class => "form_label" %>
    <%= f.select :category_id, Category.all.collect {|c| [c.name, c.id] } %><br />
    <%= f.label :description, :class => "form_label" %>
    <%= f.text_area :description, :cols => 35, :rows => 5 %>
  </p>
  <%= f.submit "Create" %>
<% end %>

app/views/topics/show.html.erb
<p><%= link_to "Main", "/" %> &gt; <%= link_to @topic.category.name, category_url(@topic.category) %> &gt; <%= @topic.title %></p>

<%= render :partial => "/topics/topic", :locals => { :topic => @topic } %>

<h3>Comments</h3>

<% if current_user %>
  <%= form_for @comment do |f| %>
    <p>
      <%= f.label :text, "Add new comment" %><br />
      <%= f.hidden_field :topic_id, :value => @topic.id %>
      <%= f.text_area :text, :cols => 50, :rows => 5, :placeholder => "Write a comment on this topic." %>
    </p>
    <%= submit_tag :login, :value => "Submit" %>
  <% end %>
<% end %>

<% if @comments && @comments.any? %>
  <%= for_each_children(@comments, nil, '<div class="comment_container">', "</div>") do |child| %>
    <% render :partial => "/comments/comment", :locals => { :comment => child, :include_topic => false } %>
  <% end %>
<% else %>
  <p>There are no comments yet.</p>
<% end %>