config/routes.rb
Agora::Application.routes.draw do
  get "sessions/create" => "sessions#create", :as => :create_session
  get "sessions/destroy" => "sessions#destroy", :as => :destroy_session

  get "categories/search" => "categories#search", :as => :search_categories

  get "users/edit" => "users#edit", :as => :edit_user
  get "users/get_reset_key" => "users#get_reset_key", :as => :get_reset_key
  post "users/send_reset_key" => "users#send_reset_key", :as => :send_reset_key
  get "users/reset_password/:id/:reset_key" => "users#reset_password", :as => :reset_password

  get "topics/new/:category_id" => "topics#new", :as => :new_topic

  get "categories/:id/subscribe" => "categories#subscribe", :as => :subscribe_category
  get "categories/:id/unsubscribe" => "categories#unsubscribe", :as => :unsubscribe_category

  post "comments/:id/reply" => "comments#reply", :as => :reply_comment
  get "comments/:id/delete" => "comments#delete", :as => :delete_comment

  post "topics/vote/:id/:positive" => "topics#vote", :as => :vote_topic
  post "comments/vote/:id/:positive" => "comments#vote", :as => :vote_comment

  resources :users
  resources :categories
  resources :topics
  resources :comments

  root :to => 'categories#show'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user
  has_many :topics
  attr_accessible :name, :user
  validates :name, :presence => true, :uniqueness => true
  validates :user_id, :presence => true

  def self.search(query)
    if query.blank?
      nil
    else
      find :all, :conditions => ["name LIKE ?", "%#{ query }%"]
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @filter = (params[:filter] || :popular).to_sym
    if params[:id]
      @category = Category.find params[:id]
      @topics = @category.topics
    else
      if current_user
        category_ids = Subscription.where(:user_id => current_user.id).map(&:category_id)
        @topics = Topic.where(:category_id => category_ids).all
      else
        @topics = Topic.all
      end
    end
    case @filter
      when :popular
        @topics.sort_by!{|t| t.votes }.reverse!
      when :controversial
        @topics.sort_by!{|t| (t.positive_votes - t.negative_votes).abs }
      when :new
        @topics.sort_by!{|t| t.created_at }.reverse!
    end
  end

  def new
    @category = Category.new
  end

  def create
    if current_user
      @category = Category.new(params[:category])
      @category.user = current_user
      if @category.save
        flash[:notice] = "Category created."
        redirect_to category_url(@category)
      else
        render :new
      end
    end
  end

  def search
    @query = params[:query]
    @categories = Category.search(@query)
    @topics = Topic.search(@query)
  end

  def subscribe
    if current_user
      category = Category.find params[:id]
      unless Subscription.find_by_user_id_and_category_id current_user.id, category.id
        Subscription.create(:user_id => current_user.id, :category_id => category.id)
      end
      flash[:notice] = "Subscribed to the category #{ category.name }"
      redirect_to :back
    else
      flash[:error] = "You have to be logged in to access this page."
      redirect_to :root
    end
  end

  def unsubscribe
    if current_user
      category = Category.find params[:id]
      if subscription = Subscription.find_by_user_id_and_category_id(current_user.id, category.id)
        subscription.delete
      end
      flash[:notice] = "Unsubscribed from the category #{ category.name }"
      redirect_to :back
    else
      flash[:error] = "You have to be logged in to access this page."
      redirect_to :root
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div class="container">
  <p>
    <%= link_to category.name, category_url(category), :class => "topic_link" %> (<%= pluralize(category.topics.size, "topic") %>)<br />
    Created by <%= link_to category.user.name, user_url(category.user), :class => "user_link" %> at <%= l category.created_at, :format => :long %>.
  </p>
  <% if current_user %>
    <% if Subscription.find_by_user_id_and_category_id current_user.id, category.id %>
      <%= link_to "Unsubscribe", unsubscribe_category_url(category) %>
    <% else %>
      <%= link_to "Subscribe", subscribe_category_url(category) %>
    <% end %>
  <% end %>
</div>

app/views/categories/index.html.erb
<p><%= link_to "Main", "/" %> &gt; Categories</p>

<% if current_user %>
  <%= link_to "Create new category", :action => :new %>
<% end %>

<% if @categories && @categories.any? %>
  <%= render :partial => "/categories/category", :collection => @categories %>
<% else %>
  <p>There are no categories yet.</p>
<% end %>

app/views/categories/new.html.erb
<%= render "/shared/error_messages", :target => @category %>

<p><%= link_to "Main", "/" %> &gt; Create new category</p>

<% if current_user %>
  <%= form_for @category do |f| %>
    <p>
      <%= f.label :name, :class => "form_label" %>
      <%= f.text_field :name %>
    </p>
    <%= f.submit "Create" %>
  <% end %>
<% else %>
  <p>You have to be logged in to access this page.</p>
<% end %>

app/views/categories/search.html.erb
<p><%= link_to "Main", "/" %> &gt; Search for "<%= @query %>"</p>

<h3>Categories</h3>
<% if @categories && @categories.any? %>
  <%= render :partial => "/categories/category", :collection => @categories %>
<% else %>
  <p>No category found.</p>
<% end %>

<h3>Topics</h3>
<% if @topics && @topics.any? %>
  <%= render :partial => "/topics/topic", :collection => @topics %>
<% else %>
  <p>No topic found.</p>
<% end %>

app/views/categories/show.html.erb
<p>
  <% if @category %>
    <%= link_to "Main", "/" %> &gt; <%= @category.name %>
  <% elsif current_user %>
    <%= link_to "Main", "/" %> &gt; Subscriptions
  <% else %>
    <%= link_to "Main", "/" %> &gt; Topics
  <% end %>
</p>

<% if current_user && @category %>
  <%= link_to "Create new topic", new_topic_url(@category.id) %><br />
  <% if Subscription.find_by_user_id_and_category_id current_user.id, @category.id %>
    <%= link_to "Unsubscribe", unsubscribe_category_url(@category) %>
  <% else %>
    <%= link_to "Subscribe", subscribe_category_url(@category) %>
  <% end %>
<% end %>

<% if @topics && @topics.any? %>
  <ul id="filters">
    <% [:popular, :controversial, :new].each do |filter| %>
      <li>
        <a href="?filter=<%= filter %>">
          <div class="filter" <%= 'id="current_filter"'.html_safe if @filter == filter %>>
            <%= filter.capitalize %>
          </div>
        </a>
      </li>
    <% end %>
  </ul>
  <div id="topics">
    <%= render :partial => "/topics/topic", :collection => @topics %>
  </div>
<% elsif current_user && !@category %>
  <p>You don't have any subscriptions yet. See the <%= link_to "list of categories", :categories %> and subscribe to some of them.</p>
<% else %>
  <p>There are no topics yet.</p>
<% end %>