config/routes.rb
Agora::Application.routes.draw do
  get "sessions/create" => "sessions#create", :as => :create_session
  get "sessions/destroy" => "sessions#destroy", :as => :destroy_session

  get "categories/search" => "categories#search", :as => :search_categories

  get "users/edit" => "users#edit", :as => :edit_user
  get "users/get_reset_key" => "users#get_reset_key", :as => :get_reset_key
  post "users/send_reset_key" => "users#send_reset_key", :as => :send_reset_key
  get "users/reset_password/:id/:reset_key" => "users#reset_password", :as => :reset_password

  get "topics/new/:category_id" => "topics#new", :as => :new_topic

  get "categories/:id/subscribe" => "categories#subscribe", :as => :subscribe_category
  get "categories/:id/unsubscribe" => "categories#unsubscribe", :as => :unsubscribe_category

  post "comments/:id/reply" => "comments#reply", :as => :reply_comment
  get "comments/:id/delete" => "comments#delete", :as => :delete_comment

  post "topics/vote/:id/:positive" => "topics#vote", :as => :vote_topic
  post "comments/vote/:id/:positive" => "comments#vote", :as => :vote_comment

  resources :users
  resources :categories
  resources :topics
  resources :comments

  root :to => 'categories#show'

  match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Agora</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <h1 id="title"><%= link_to "Agora", "/" %></h1>
  <div id="right">
    <% if current_user %>
      Logged in as <%= link_to current_user.name, user_url(current_user), :class => "user_link" %>.
      <%= link_to "Options", edit_user_url %>
      <%= link_to "Logout", :destroy_session %>
    <% else %>
      <%= render "/sessions/new" %>
    <% end %>
    <br />
    <%= form_tag :search_categories, :method => :get do %>
      <%= text_field_tag :query, "", :placeholder => "Search for categories and topics", :id => "search_field" %>
      <%= submit_tag "Search" %>
    <% end %>
    <br />
    <%= link_to "Categories", url_for(:controller => :categories, :action => :index) %>
  </div>
</header>

<div id="flash">
  <% if flash[:error] %>
    <div id="error">
      <%= flash[:error] %>
      <div class="dismiss_flash"><a href="#" id="dismiss_error">Dismiss</a></div>
    </div>
  <% end %>
  <% if flash[:notice] %>
    <div id="notice">
      <%= flash[:notice] %>
      <div class="dismiss_flash"><a href="#" id="dismiss_notice">Dismiss</a></div>
    </div>
  <% end %>
</div>

<div id="content">
  <%= yield %>
</div>

<footer>
  <p>Agora, 2012.</p>
</footer>

</body>
</html>